### ISSUE TITLE
[Bug] wrong time displayed

### ISSUE THREAD

**Issue by zekabra** [JGeek00/adguard-home-manager#21] opened 2022-11-24 00:32 UTC
Server has the correct time, docker container has the correct time, Adguard Home shows the correct time, android devices where I run Adguard Home manager app have the correct time, but the app shows the time with an hour difference 

![Screenshot_2022-11-23-01-58-54-107_com jgeek00 adguard_home_manager](https://user-images.githubusercontent.com/24387750/203668460-ea124143-2159-4548-b986-bb16fa837187.jpg)
![Screenshot_2022-11-23-01-58-31-352_com kiwibrowser browser](https://user-images.githubusercontent.com/24387750/203668465-5aea6fff-f8fd-4700-aaa7-b91ab60c984c.jpg)

**Comment by JGeek00** [comment] 2022-11-24 01:09
That's a known issue. I have seen many times during the development. On mu device the application shows the correct time. Maybe could be something related with the time zone, but I will need to investigate it.

**Comment by zekabra** [comment] 2022-11-24 02:14
> That's a known issue. I have seen many times during the development. On mu device the application shows the correct time. Maybe could be something related with the time zone, but I will need to investigate it.

time zones are correct on all devices, a solution would be to have in the app an option to use the server time or to be able to select the time zone, which would be useful when you are traveling in a zone with another time zone, this of course for people who have adguard home configured to use outside home

**Comment by JGeek00** [comment] 2022-11-24 08:53
@zekabra could you give me your time zone? Just for testing.

**Comment by zekabra** [comment] 2022-11-24 21:13
It's GMT+00:00

**Comment by zekabra** [comment] 2022-11-24 22:06
more information to help troubleshoot the problem, tested on 2 devices. Currently the app has one hour more, unchecked the option for the time and time zone to be automatically provided by the network, nothing changed, manually selected a time zone with +01:00, my time increased but the app kept the time unchanged, manually selected again +00:00, this time the app showed the correct time and my equipment also has the correct time, I selected again time and time zone automatically provided by the network, in one equipment the app kept the correct time but in another it increased one hour

**Comment by JGeek00** [comment] 2022-11-26 20:57
I don't have that issue. On my case I'm on GMT+1 and the app shows the correct time. If I switch to GMT+0 the app still shows the correct time. When you change the timezone on the device settings, you have to refresh the logs list to update the time.

When the app shows a different time than the web app, go to the web app, to the logs list, open developer tools, and on the network tan, open the ``querylog``request. There, on the response, open one log and paste here the time.

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/47545344/204108614-e6c1ea25-95c4-4ea7-b6bd-ae53325181aa.png">

**Comment by zekabra** [comment] 2022-11-27 15:40
I can't find the entry in the web app to view the log, can you provide more directions. Video showing the problem, Lineage 18.1 rom, never had problems with timezones in other apps.

https://martinhojose.dynip.sapo.pt/s/zQEaZxNfxTYAg4B

**Comment by JGeek00** [comment] 2022-11-27 15:53
As I can see the issue is only present on Lisbon timezone on Portugal. I tried many other timezones on the US, India, China with no issues. Also as you can see, the Canary Islands are also on GMT+0 and with that timezone selected there's no issue. It's very strange.


https://user-images.githubusercontent.com/47545344/204144443-6eb3f3b1-6e85-4b8b-a1a7-a86982c64d5d.mp4

**Comment by zekabra** [comment] 2022-11-27 16:08
So it seems, I tried with a larger time zone and the time was shown correctly, when I went back to mine, the time went back to showing 1 hour more, as you suggested, I tried with Spain/Canary and it shows the correct time, for now I will use that setting until the cause of the bug is found, thanks for the support

**Comment by JGeek00** [comment] 2022-11-27 16:16
The issue seems to be fixed

https://user-images.githubusercontent.com/47545344/204145581-5cdea923-6de0-422c-a041-d03ea28d9757.mp4

**Comment by zekabra** [comment] 2022-11-27 16:29
> The issue seems to be fixed
> 
>  Grabacion.de.pantalla.2022-11-27.a.las.17.13.39.mp4

Thank you very much for your patience and dedication

**Comment by JGeek00** [comment] 2022-11-27 16:32
Fixed on v1.5.3. I have uploaded the update to Google Play a moment ago. It should be available later today. Thank you for reporting the issue and I hope you enjoy the application.

**Closed by JGeek00** 2022-11-27 16:32 UTC
Labels: bug
