### ISSUE TITLE
[Bug] Charts not displaying properly

### ISSUE THREAD

**Issue by zutzo** [JGeek00/adguard-home-manager#55] opened 2023-08-07 01:48 UTC
Charts not displaying properly
Connect local:
![](https://github.com/JGeek00/adguard-home-manager/assets/126886178/54d46122-4433-488b-abe4-b0a94589d5d0)
Connect server:
![](https://github.com/JGeek00/adguard-home-manager/assets/126886178/817e54cd-8540-483f-8856-8814753c4676)
When I dock my mouse on the chart
![](https://github.com/JGeek00/adguard-home-manager/assets/126886178/6dd8c9b8-ce90-4925-b0cc-287be0abaa58)

I think its a bug
If you need more information,pls tell me

App version:2.7.0
All ADGH version:v0.107.36

**Comment by JGeek00** [comment] 2023-08-28 18:19
I will release v2.7.1 soon. Let me know if the issue is still there on that version.

**Comment by JGeek00** [comment] 2023-09-04 21:46
It should be fixed on the next update.

**Comment by JGeek00** [comment] 2023-10-04 17:11
I have just released v2.8.0. Check if it's fixed please.

**Comment by JGeek00** [comment] 2023-10-05 08:19
It's fixed on v2.8.1. Thank you for reporting.

**Closed as completed** 2023-10-05 13:09 UTC
Labels: bug
